### ISSUE TITLE
Question: What happened to largest/shortest times?

### ISSUE THREAD

**Issue by weavage** [rfmoz/tuptime#73]
I see where the largest and shortest up/down times got removed in version 5, but what was the reasoning? Are there plans to add it back in? I love that metric!

**Comment by rfrail3** [comment]
Hi Weavage.

The largest and shortest up/down times was on the default output for a long time. But trying to keep a clean and useful output, I realised that both rarely change and their functionality overlap the "order" option. As an examples:

Order by short downtime:

`tuptime -t -o d -r`

...by large downtime:

`tuptime -t -o d` 

...by short uptime:

`tuptime -t -o u -r`

... or by large uptime:

`tuptime -t -o u`

Also, the "order" option provides other facilities to work with: r-runtime, s-sleep time, e-end status, k-kernel. And it's possible to use list output `-l` instead of table `-t`.

**Comment by rfrail3** [comment]
Last release 5.2.1 have "Longest uptime" and "Longest downtime" back on the default output, as before.

Also, next 5.2.2 will have "Shortest uptime" and "Shortest downtime" swich if the argument "-r" is used on the default output.
