### ISSUE TITLE
Feature request: Graceful uptime

### ISSUE THREAD

**Issue by mschmitt** [rfmoz/tuptime#85]
I'm interested in finding the uptime since the most recent non-graceful shutdown. My systems do automated regular reboots, so any uptime since a non-graceful shutdown would be my "graceful uptime".

```
$ tuptime --table | grep --after-context 1 BAD | grep -v BAD  | tail -1
  3   20:59:06 21.02.2024    7m 31s   21:06:37 21.02.2024   OK         16s
```

Returns the first boot after the most recent non-graceful shutdown, which can in turn be used for the `--since` option:

```
$ tuptime --since "$(tuptime --table | grep --after-context 1 BAD | grep -v BAD  | tail -1 | awk '{print $1}')"
System startups: 	2  since  20:59:06 21.02.2024
System shutdowns: 	1 ok  +  0 bad
System life: 	        19m 56s

Longest uptime: 	12m 9s  from  21:06:53 21.02.2024
Average uptime: 	9m 50s
System uptime: 	        98.66%  =  19m 40s

Longest downtime: 	16s  from  21:06:37 21.02.2024
Average downtime: 	16s
System downtime: 	1.34%  =  16s

Current uptime: 	12m 9s  since  21:06:53 21.02.2024
```

I personally think that this concept of "graceful uptime" would fit perfectly into tuptime's default output, but a new option along the lines of `--since-non-graceful`, limiting the view to start at the first boot since the most recent non-graceful shutdown, would be just as fine.

Does any of this make sense? :-)

**Comment by rfmoz** [comment]
Hello Martin,

Thanks for present your case, it's always interesting to know the different ways of using Tuptime.

The requirement proposed falls into a type of filtering that could be called "advance filtering", because it is possible to normalize it to the point of reaching a register ID or a timestamp, any of them already covered by existing arguments, like `--until`, `--since`, `--at`, `--exclude`, `--tsince`, `--tuntil`, `--tat`.

Please, let me summarize, plus yours, a few other examples that I've know:

- --since-non-graceful  - Since the startup following the most recent non-graceful shutdown.
- --skip-bad-shutdown  - All startups with a clean shutdown.
- --only-bad-shutdown  - All startups with a bad shutdown.
- --last-bad-shutdown  - Indentify only the last register when the system had a non-graceul shutdown.

And also with time:

- --since-last [month|week|day] - Report usual time ranges.

In some environments, like yours, they offer the key to use Tuptime, but they are like shortcuts. Tuptime offers strong and reliable primitives to construct basic filtering, allowing users to narrow down the range in any way they imagine.

If it offers one of these options, why not other that could be essential in other environment? At the end, the proyect would move away the good design trends, like [Unix Philosophy](http://www.catb.org/~esr/writings/taoup/html/ch01s06.html)  and [Suckless Philosophy ](https://suckless.org/philosophy/)

Anyway, to offer an alternative, if you put this little script in a folder listed in your $PATH before "/usr/bin", for example "/usr/local/bin" you'll have the expected behaviour.

```
#!/bin/bash

EXE='/usr/bin/tuptime'

# Process new argument if it exists
if [[ "$1" == "--since-non-graceful" ]]; then

        # Remove it from argument list
        set -- "${@/--since-non-graceful/}"

        # Set argument value:
        #  - Order table by 'e'nd status
        #  - Grep last BAD register
        #  - Increase in 1 their No.
        VAL1=`$EXE --table --order e | grep BAD | tail -1 | awk '{print $1 + 1}'`

        # Set new behaviour
        if [ -n "$VAL1" ]; then
                set -- "$@" "--since" "$VAL1"
        fi
fi

# Call with arguments 
$EXE $@
```
Also, I slighly improve your filter using `--order e` to avoid one pipe step.

Now, executing it with the new argument will produce the expected result:

`$ tuptime --since-non-graceful`

**Comment by mschmitt** [comment]
Thanks for your feedback!

My request is totally not in the `--last-year` class, because this seems to be flawlessly covered by `--tsince` and `--tuntil`, but now that you outlined a few additional use cases, `--since-previous-graceful-until-previous-non-graceful` would be something I could see myself also being interested in. ;-)

I'll test a shell function that does the filtering. :-)

```
function tuptime-graceful () {
        local tuptime_since=1
        local temp_array
        while read -r line 
        do
                if [[ "${line}" =~ ' BAD ' ]]
                then
                        read -r -a temp_array <<< "${line}"
                        tuptime_since=$(( temp_array[0] + 1 ))
                        break
                fi
        done < <(tuptime --table --order e --reverse)
        tuptime --since "${tuptime_since}"
}
```
